name: Build and Run Docker Containers

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 3000:80
          - 5000:8080

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and run services
        run: |
          docker-compose -f docker-compose.yml up -d

      - name: Keep the job running
        run: |
          echo "Containers are running."
          tail -f /dev/null
