version: '3.8'

services:
  frontend:
    build:
      context: ./NoBullshitReviews.Frontend
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network

  backend:
    build:
      context: ./NoBullshitReviews.Api
      dockerfile: dockerfile
    ports:
      - "5000:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
