name: Deploy to VPS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy Docker Compose to VPS
        run: |
          sudo apt-get install -y sshpass
          sshpass -p "${{ secrets.VPS_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} << 'EOF'

            cd /var/www/nobullshitreviews
            if [ ! -d .git ]; then
              git clone git@github.com:Puzonn/NoBullshitReviews.git
            fi

            git checkout main

            git pull origin

            cd NoBullshitReviews

            docker-compose up --build
          EOF
