name: Deploy to VPS

on:
  push:
    branches:
      - github-actions
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22

      - name: Deploy Docker Compose to VPS
run: |
    sudo apt-get install -y sshpass
    sshpass -p "${{ secrets.VPS_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} << 'EOF'
      cd /path/to/your/project

      git pull origin main

      docker-compose build
      docker-compose up -d
    EOF
