name: Build and Deploy Docker Compose to VPS

on:
  push:
    branches:
      - github-actions

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/puzonne/nobullshitreviews:latest .
          docker push ghcr.io/puzonne/nobullshitreviews:latest

      - name: Set up SSH
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22

      - name: Deploy Docker Compose to VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} << 'EOF'
            cd /path/to/your/project
            git pull origin main  # Pull the latest code from your GitHub repo
            docker-compose pull    # Pull the latest images
            docker-compose up -d   # Restart the services in detached mode
          EOF
